apiVersion: v1
kind: Service
metadata:
  name: channel-aggregation-decisioning-processor-rel-1-0-0
  namespace: processor
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: channel-aggregation-decisioning-processor
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
