#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

sed -i "s|ENV CODEVERSION=.*|ENV CODEVERSION= |g" Dockerfile

# Define the variable name and the new value
VARIABLE_NAME="CODEVERSION"
LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")

# Specify the Dockerfile path
DOCKERFILE="Dockerfile"

# Use sed to replace the variable value in the Dockerfile
sed -i "s|ENV CODEVERSION=|ENV CODEVERSION=\"$LAST_COMMIT_MESSAGE\" |g" Dockerfile

# Stage the modified Dockerfile
git add Dockerfile


npx lint-staged
