#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define the variable name and the new value
VARIABLE_NAME="CODEVERSION"
LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")

# Specify the Dockerfile path
DOCKERFILE="Dockerfile"

# Use sed to replace the variable value in the Dockerfile
sed -i "s|ENV CODEVERSION=|ENV CODEVERSION="$(git log -1 --pretty=format:"%s")" |g" Dockerfile

# Stage the modified Dockerfile
git add Dockerfile

git commit -M "$(git log -1 --pretty=format:"%s") Code Version"


npm test

exit 0
